version: "3"
services:
  my-spring-boot:
    build: my-spring-boot/
    image: sample-sb03
    container_name: sample-sb03
    ports:
      - 18080:8080
    links:
      - my-elasticsearch
  my-elasticsearch:
    build: my-elasticsearch/
    image: sample-es03
    container_name: sample-es03
    ports:
      - 19200:9200
