version: "3"
services:
  my-spring-boot:
    build: my-spring-boot/
    image: sample-sb04
    container_name: sample-sb04
    ports:
      - 48080:8080
    links:
      - my-elasticsearch
  my-elasticsearch:
    image: shinyashikis/my-elasticsearch7:0.0.1
    container_name: sample-es04
    ports:
      - 49200:9200
